name: bilibili rank

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  bilibili-rank:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Run
        run: |
          pnpm run build

      - name: Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "docs: update README" || exit 0
          git push origin main