name: bilibili rank

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  bilibili-rank:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Run
        run: |
          pnpm run build

      - name: Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "feat: update bilibili-rank" || exit 0
          git push origin main
      - name: Copy
        run: |
          mkdir ./public
          cp ./index.html ./public/
          cp -r ./assets/ ./public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
